### ISSUE TITLE
geeqie crashes with segv on NEF files

### ISSUE THREAD

**Issue by lechucklives** [BestImageViewer/geeqie#1123]
### ISSUE TYPE

* Bug Report

### GEEQIE VERSION

```
$ geeqie --version
Geeqie 2.0.1 GTK3
```

```
GTK3
```

### OS / DISTRIBUTION
only tested on Arch Linux
(ldd output attached)

[geeqie_gdb.txt](https://github.com/BestImageViewer/geeqie/files/11885772/geeqie_gdb.txt)
[geeqie_ldd.txt](https://github.com/BestImageViewer/geeqie/files/11885773/geeqie_ldd.txt)
[geeqie_strace.txt](https://github.com/BestImageViewer/geeqie/files/11885774/geeqie_strace.txt)
[geeqie_version.txt](https://github.com/BestImageViewer/geeqie/files/11885776/geeqie_version.txt)

### SUMMARY

Geeqie crashes with SEGV upon startup, if NEF (Nikon Extended Format, Nikon's raw photo file format) is present
Geeqie runs fine if no NEF files are present
If geeqie is running, and from the interface a directory with one or more NEFs is opened, it briefly displays the first NEF, then crashes. It therefore can parse NEF files successfully, it seems. Not certain how to proceed.

### STEPS TO REPRODUCE

any file pointer given on command line, or directory read with NEF files, causes this.
strace, gdb, ldd output attached to this report

**Comment by caclark** [comment]
I think the problem is that you are using exiv2 0.28.0. Reverting to 0.27.6 will avoid the problem.

This was fixed in commit c45cca777a.

If you have an interest, see also https://github.com/BestImageViewer/geeqie/issues/1090 and https://github.com/BestImageViewer/geeqie/issues/1105 for the history.

**Comment by lechucklives** [comment]
Thanks!
By downgrading 4 packages I could indeed restore functionality

**Comment by xiota** [comment]
Also using Arch.  Similar issue, but using `raf` files.  Built 03c53ea6f239d13333eddc5affdfd856d0688f8c.  Still crashes.

@lechucklives Which four packages did you downgrade?

**Comment by lechucklives** [comment]
> Also using Arch. Similar issue, but using `raf` files. Built [03c53ea](https://github.com/BestImageViewer/geeqie/commit/03c53ea6f239d13333eddc5affdfd856d0688f8c). Still crashes.
> 
> @lechucklives Which four packages did you downgrade?
I reverted these 4 packages to the versions below:
exiv2-0.27.6-2-x86_64.pkg.tar.zst
geeqie-2.0.1-5-x86_64.pkg.tar.zst
libexif-0.6.23-1-x86_64.pkg.tar.zst
libgexiv2-0.14.0-4-x86_64.pkg.tar.zst

Keep in mind that you  may have more dependencies, e.g. exiv2  is likely to be used by any photo manipulation / processing software you might have installed, such as DarkTable.
