### ISSUE TITLE
Support heic image format

### ISSUE THREAD

**Issue by davidsgrogan** [BestImageViewer/geeqie#610]
### ISSUE TYPE

* Feature Request

### GEEQIE VERSION

```
Geeqie 1.3
```

```
GTK version: don't know, but probably irrelevant here?
```

### OS / DISTRIBUTION

Debian testing

### SUMMARY
Add support for .heic image files, which is the default produced by recent iPhone versions.

### STEPS TO REPRODUCE

Add a .jpg and a .heic file to a directory. Start geeqie in the directory. Only the .jpg is shown in the list to the left.

**Comment by schreiberste** [comment]
Libheif (https://github.com/strukturag/libheif) seems like a good place to look at when trying to add HEIC support.

**Comment by caclark** [comment]
Attached is a .diff of a quick hack to display .heic images using libheif.
Only the primary image is displayed (but that will not change), maybe the thumbnails are not created, and the icon is incorrect.
To compile it you will need to install libheif and libheif-dev.
When running Geeqie you may also need to go to Edit/Preferences/Files and insert a new item - file type .heic and class Heif.

I have tried it on only a couple of files. If someone tries this and it fails on something, please let me know.
As always, I am not sure when I can get around to completing this....
[heif_1.diff.gz](https://github.com/BestImageViewer/geeqie/files/3351889/heif_1.diff.gz)

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=115f9840c030daeaaf7a5095b00b874a3c737efb

**Comment by schreiberste** [comment]
Thank you so much for considering this and implementing heif support!

**Comment by caclark** [comment]
Thanks for pointing out libheif.

Is there a real need for displaying all images in a container - is multiple images in a container common practice?
And if so, what should the user-interface look like?

**Comment by schreiberste** [comment]
> Is there a real need for displaying all images in a container - is multiple images in a container common practice?

To be honest - I have no idea. My use case is just looking at photos taken with an iPhone. In this case, there is only one image.
There is the "live-photo" feature that records a very short video when taking a photo. I didn't really use this yet, so I'm not even sure if the "live-photo" will not end up in a .mov file?
But I guess for an image viewer it's perfectly fine to just show the first image anyway.

**Comment by caclark** [comment]
Delete HEIF class. Use magic number to make .heic files class Image
Commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=93e6dd0df6308769bc62140110dc0bfa490e060a

**Comment by dandv** [comment]
Please add HEIC to the list of supported image format at http://www.geeqie.org/features.html (before #226 is completed, ideally). I've been looking for an image viewer that supports HEIC specifically, and based on that page, I would've skipped Geeqie.

**Comment by eharris** [comment]
Even though this was fixed 7 months ago, and there have been releases since then, it doesn't look like this has made it into a release yet.  When will there be a release including HEIC/HEIF support?

**Comment by ChrisCheney** [comment]
Just wondering if there is going to be a new geeqie release with heic support in it?

The heic code was added a year ago but still isn't in the released version, which is currently still 1.5.1.

**Comment by Yenya** [comment]
Just a me too for comment by @ChrisCheney. I wanted heif/heic support in Fedora, but Fedora developers say that they will package a released version of geeqie only, not an unreleased state in the master branch:

https://bugzilla.redhat.com/show_bug.cgi?id=1767080

Could you please make a release soon? Thanks in advance.

**Comment by caclark** [comment]
If your system can run AppImages, please see this post:
https://www.freelists.org/post/geeqie/Geeqie-AppImages

**Comment by bio12** [comment]
thumbnails are not created. Using 1.5.1+git20200808-2a27c9ab (Standard Ubuntu Package for 20.10)

**Comment by caclark** [comment]
> thumbnails are not created. Using 1.5.1+git20200808-2a27c9ab (Standard Ubuntu Package for 20.10)

Heic support is included in Geeqie v1.6. That will be in Ubuntu 21.04 which is scheduled for release in April.
The only immediate solution is to compile from sources - there is a script to do this for Ubuntu systems.

**Comment by bio12** [comment]
Thank you. I tried the AppImage above. Thumbnails are created. But no exif data is shown. Do you know, if it is fixed in the 1.6? If so I would spend time to compile from the source.
btw I use a S10+ and soon a Canon R5, which both creates heic images.

**Comment by caclark** [comment]
The exif data display relies on the exiv2 project, which does not handle heic data. The next release of exiv2 will do so - also sometime around April I think.

**Comment by bio12** [comment]
Thank you very much caclark!
