### ISSUE TITLE
Image preview does not update when pressing shift-up

### ISSUE THREAD

**Issue by gaul** [BestImageViewer/geeqie#713]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 1.4
```

```
GTK 3.24.8
```

### OS / DISTRIBUTION
Fedora 30

### SUMMARY
Image preview does not update when pressing shift-up.

### STEPS TO REPRODUCE
When pressing shift-down, down, or up the image updates.  When pressing shift-up, it does not, except when the focus is part of the original selection.

I am happy to fix this but am having trouble figuring out where to start.  Any pointers?

**Comment by caclark** [comment]
Unfortunately there is no documentation.

Some idea of where objects are defined can be found with the GTK Inspector:
GTK_DEBUG=interactive src/geeqie
(... but not much help in this instance)

The menu items are defined in src/layout_util.c, from line 1900 onwards
(... also not much help in this instance)

In this case all you can do is a global search on GDK_KEY_Up and GDK_SHIFT_MASK, and take a guess at which module is the most likely culprit.

Thanks for the offer of help.

**Comment by gaul** [comment]
While researching this I found that geeqie does not act how I expect when pressing control up and down.  Other Gtk apps move the focus and allow selection with space bar.  When pressing control down, geeqie moves the focus one and when pressing it again it selects that element.

**Comment by caclark** [comment]
The shift-up problem is fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=14d8ce4568a651939b8ffd12f4ea50b0635b9589

The control up/down function seems to work as expected on my system.

**Comment by caclark** [comment]
There is nothing in this commit that changes image display. 
You make a total clean by:
sudo make maintainer-clean
You can also try:
autogen.sh --disable-gtk3
And you can try a previous version by:
git checkout v1.4

I hope something there gives a clue about the problem

**Comment by gaul** [comment]
` autogen.sh --disable-gtk3` resolved the gray image problem.  I can confirm that 14d8ce4568a651939b8ffd12f4ea50b0635b9589 fixed the shift-up and -down issue.  The control-up and -down issue remains.  Thanks for fixing this!  Should I open a new issue for the other symptom or continue to track it in this one?

**Comment by caclark** [comment]
The subject of this issue is solved, so it would be better to open a new one for the other problem.
Thanks.
