### ISSUE TITLE
Allow to display keyboard shortcut within menu item 

### ISSUE THREAD

**Issue by przepompownia** [BestImageViewer/geeqie#732]
### ISSUE TYPE
* Feature Request

### GEEQIE VERSION
0d08a02

### SUMMARY
When I open context menu, I would like to see assigned (by preferences or plugin definitions) keyboard shortcuts to learn them and minimize using the menu in the future. It is implemented in the main menu, but not in the context menu.

**Comment by caclark** [comment]
The shortcuts are also shown in the Search and Run function (if you are compiling the latest version from sources).

**Comment by przepompownia** [comment]
SaR is very helpful, independently. :+1:

**Comment by caclark** [comment]
Fixed in commit 1879fc929a

**Comment by przepompownia** [comment]
Thanks, although the shortcuts are still not present in right-click context menu:

![image](https://user-images.githubusercontent.com/11404453/176481477-be5d5604-7c34-40ad-a894-75e7b77f98bf.png)
![image](https://user-images.githubusercontent.com/11404453/176482144-04116577-983c-4a32-9aff-c165d5a51e58.png)
![image](https://user-images.githubusercontent.com/11404453/176481793-8ba5df23-d637-46dc-b8b4-f2cac49bd050.png)

**Comment by przepompownia** [comment]
![image](https://user-images.githubusercontent.com/11404453/176676247-ce376a43-917a-41b9-8289-001c2ec1046c.png)
Thanks again!
