### ISSUE TITLE
Crash when creating new dir with same name as already existing file

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#741]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION

```
Geeqie 1.5.1
```

### OS / DISTRIBUTION
Debian Unstable

### SUMMARY

Trying to create a folder with the same name as an already existing file causes geeqie to crash, and locks my X. 

ERROR:filedata.c:654:file_data_new_dir: assertion failed: (S_ISDIR(st.st_mode))
Bail out! ERROR:filedata.c:654:file_data_new_dir: assertion failed: (S_ISDIR(st.st_mode))

See Debian bug 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948293

### STEPS TO REPRODUCE
go to some temp directory
create a file using "touch 1"
start geeqie
Right click on your folder, select "New folder"
and name it "1".

**Comment by caclark** [comment]
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=ee5cc947e0605932eb141f42e06b2ff1dc3d1b4e

**Comment by gusnan** [comment]
I am sorry to say, this didn't solve it for me.

I still get

`gusnan@debian-buildsystem:~/temp/geeqie > /usr/bin/geeqie
**
ERROR:filedata.c:654:file_data_new_dir: assertion failed: (S_ISDIR(st.st_mode))
Bail out! ERROR:filedata.c:654:file_data_new_dir: assertion failed: (S_ISDIR(st.st_mode))
Avbruten (SIGABRT)
`

And if I try to debug with gdb, it completely locks X.

**Comment by caclark** [comment]
Ah, sorry. Using the test case supplied by the user instead of my own test case would seem to be sensible.
http://www.geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=44ca3574b1f95d8217ca272c254b054914bdf247

**Comment by gusnan** [comment]
Thanks - now it works. Your work is greatly appreciated.
